services:
  admetica-api:
    image: docker.io/cadavidesteban/admetica-api:v1
    restart: unless-stopped

  crewai:
    build:
      context: science_agent
      dockerfile: ../Dockerfile
    command: uv run crewai run
    environment:
      - OPENAI_API_KEY=<YOUR_API_KEY>
      - MODEL="gpt-4o"
      - ADMETICA_API=http://admetica-api:8080
      - INPUT_CSV="./sample_data.csv"
      - REPORT_FILE="/app/output/report.md"
    volumes:
      - "./output:/app/output"
